@startuml

title __MODEL's Class Diagram__\n


      namespace model {
        interface com.example.mkv_build.model.Builder {
            {abstract} + build()
            {abstract} + drawRectBackground()
            {abstract} + drawRectIndicator()
            {abstract} + drawStartStopLabel()
            {abstract} + drawTitle()
        }
      }

  


      namespace model {
        class com.example.mkv_build.model.ConcreteBuilder {
            - ktemp : int
            - start : float
            - stop : float
            + ConcreteBuilder()
            + build()
            + drawRectBackground()
            + drawRectIndicator()
            + drawStartStopLabel()
            + drawTitle()
        }
      }

  


      namespace model {
        class com.example.mkv_build.model.Director {
            + Director()
            + construct()
        }
      }

  


      namespace model {
        class com.example.mkv_build.model.Indicator {
            - label_end : Label
            - label_point : Label
            - label_start : Label
            - label_title : Label
            - panel : Pane
            - rectangle_background : Rectangle
            - rectangle_indicator : Rectangle
            + Indicator()
            + add()
            + getLabel_end()
            + getLabel_point()
            + getLabel_start()
            + getLabel_title()
            + getRectangle_background()
            + getRectangle_indicator()
            + setLabel_end()
            + setLabel_point()
            + setLabel_start()
            + setLabel_title()
            + setRectangle_background()
            + setRectangle_indicator()
            + show()
        }
      }

  

  com.example.mkv_build.model.ConcreteBuilder .up.|> com.example.mkv_build.model.Builder
  com.example.mkv_build.model.ConcreteBuilder o-- com.example.mkv_build.model.Indicator : indicator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
