@startuml

title __MODEL's Class Diagram__\n


      namespace model {
        class com.example.mkv_watch.model.Colors {
            - b : int
            - r : int
            - random : Random
            - y : int
            + update()
            ~ Colors()
        }
      }

  


      namespace model {
        class com.example.mkv_watch.model.ComponentOne {
            ~ b : int
            ~ cir : Circle
            ~ pol : Polygon
            ~ r : int
            ~ rect : Rectangle
            ~ y : int
            + ComponentOne()
            + update()
        }
      }



      namespace model {
        class com.example.mkv_watch.model.ComponentThree {
            ~ imageView : ImageView
            ~ images : List<Image>
            ~ ims : List<File>
            + ComponentThree()
            + update()
            - new_img()
        }
      }



      namespace model {
        class com.example.mkv_watch.model.ComponentTwo {
            ~ field : TextField
            + ComponentTwo()
            + update()
        }
      }

  


      namespace model {
        class com.example.mkv_watch.model.ConcreteObserver {
            - name : String
            + ConcreteObserver()
            + ConcreteObserver()
            + update()
        }
      }

  

      namespace model {
        class com.example.mkv_watch.model.ConcreteSubject {
            - observers : ArrayList<Observer>
            + attach()
            + detach()
            + notifyAllObserver()
            + tick()
        }
      }

  


      namespace model {
        interface com.example.mkv_watch.model.Observer {
            {abstract} + update()
        }
      }

  


      namespace model {
        interface com.example.mkv_watch.model.Subject {
            {abstract} + attach()
            {abstract} + detach()
            {abstract} + notifyAllObserver()
        }
      }


      namespace model {
        class com.example.mkv_watch.model.TimeServer {
            ~ observers : List<Observer>
            ~ timer : Timer
            ~ timertask : TimerTask
            + TimeServer()
            + attach()
            + detach()
            + notifyAllObserver()
            + restart()
            + start()
            + stop()
            - tick()
        }
      }

  

  com.example.mkv_watch.model.ComponentOne .up.|> com.example.mkv_watch.model.Observer
  com.example.mkv_watch.model.ComponentOne o-- com.example.mkv_watch.model.Colors : colors
  com.example.mkv_watch.model.ComponentThree .up.|> com.example.mkv_watch.model.Observer
  com.example.mkv_watch.model.ComponentTwo .up.|> com.example.mkv_watch.model.Observer
  com.example.mkv_watch.model.ConcreteObserver .up.|> com.example.mkv_watch.model.Observer
  com.example.mkv_watch.model.ConcreteSubject .up.|> com.example.mkv_watch.model.Subject
  com.example.mkv_watch.model.TimeServer .up.|> com.example.mkv_watch.model.Subject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
